# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: AshwiniRanganath2020/ReusableWorkflow/.github/workflows/build.yml@main
    with:
      image_name: ashwiniranganath2020/trivyscan
      tag: ashwiniranganath2020/trivyscan
    secrets:
      registry_username: ${{secrets.DOCKER_HUB_USERNAME}}
      registry_password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
