# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: AshwiniRanganath2020/ReusableWorkflow/.github/workflows/build.yml@main
    with:
      image_name: ashwiniranganath2020/trivyscan
      image_tag: 0
      GHCR_REPO: https://hub.docker.com/
      docker_file_path: ./ReusableWorkflow
      Packages_lock: AshwiniRanganath2020/ReusableWorkflow/package-lock.json
    secrets:
      registry_username: ${{secrets.DOCKER_HUB_USERNAME}}
      registry_password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
